[package]
name = "edgegrid-rs"
version = "0.2.8"
authors = ["FoxBoxPDX <foxboxpdx@gmail.com>"]
edition = "2018"

[dependencies]
openssl = "0.10"
time = "0.2.25"
uuid = { version = "0.8.2", features = ["v4"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
