[package]
name = "edgegrid-rs"
version = "0.1.1"
authors = ["Fox, Daniel <Daniel.Fox@nike.com>"]
edition = "2018"

[dependencies]
openssl = "0.10"
time = "0.2.25"
uuid = { version = "0.8.2", features = ["v4"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
